formatter: markdown table  # required

sections:
  hide:
    - modules
    - resources

sort:
  by: required

output:
  template: |-
    <!-- BEGIN TFDOCS -->
    {{ .Content }}

    <!-- END TFDOCS -->
