dist: focal

language: minimal

env:
  global:
    - IMAGE_NAME=tardigrade-ci-test

if: branch = master OR type = pull_request OR tag is present

stages:
  - lint
  - test
  - deploy

services:
  - docker

jobs:
  include:
    - stage: lint
      name: Project Syntax Verification
      install: make lint/install
      script: make -o docs/lint lint
    - stage: test
      name: Run Makefile unit tests
      install: docker build --build-arg GITHUB_ACCESS_TOKEN=$GITHUB_ACCESS_TOKEN -t "$IMAGE_NAME" -f Dockerfile .
      script: docker run "$IMAGE_NAME" bats/test
    - stage: deploy
      name: Deploy to GitHub Releases
      if: branch = master AND type = push AND repo = plus3it/tardigrade-ci
      before_script:
        - |
          PRIOR_VERSION=$(git describe --abbrev=0 --tags)
          RELEASE_VERSION=$(grep current_version $TRAVIS_BUILD_DIR/.bumpversion.cfg | sed 's/^.*= //' )
          RELEASE_BODY="* [tardigrade-ci v$RELEASE_VERSION CHANGELOG](https://github.com/plus3it/tardigrade-ci/blob/$RELEASE_VERSION/CHANGELOG.md)"
          export PRIOR_VERSION RELEASE_VERSION RELEASE_BODY
      script: skip
      before_deploy:
        - (set -x; git tag -a $RELEASE_VERSION -m $RELEASE_VERSION)
      deploy:
        provider: releases
        api_key:
          secure: bTyWza60D4ss26ZMLgCwq4XgyVPy2pnsyoR3rKJDvyPkyVze+Xyx+c6B2Qx6WknYdEnAd4ESrruI3FwISpldv3knIBm2HdfuZlzJkqtDxKCLqieNjuP/Z1tmWiznNq0MvtfWe/nN4JPg+Bcj8d1+RVN/XiuNrRnnIFP5aKRzrB38xzFP/lKXMkd8YokZI3vfQ/hVjZASxcTPx1n823bDKIjEHAL7lpGRN0JmG3KU2Fq6rjvwQyRJGCQ0xDsNO+9/frDmwKbVT0oYCUpxm13z0f4MQNembots/IyvT53g+0G8o9IQ2S69cOHmaQAZSylLuH/4sHuGBkXxhM8/YHbS4bdSTny3jHq6BmWAtYeo2YS/0sdLY6gBGJ5+D1/7e69QqnuIOsFviWjvURWVpcUAWzdsE4ZBTEtfF6IcLbULng4CVcexZsmuUDpuDWAFhvZZBkPKUXm79/YL3gpKPaziW7TGIku2ZMfq/dXPTBWOdnrQwl3LZOE6X15nbbKH/gvPh33fCVENp1n2hCYIpW78rZo0C2QjDyqutggDV+kC4k0GYcXQWP9U7K4bOTkHLh4j4R2vBpfDvMvqGClciTfsgLReAaC3bWBs8Zy5hefrIKQcZw1DLcHtKv3QjTzcnhHgllDeH+yubSP2eXgNA8/WW0zOf518KXHAAO2KW9WYdX4=
        name: $RELEASE_VERSION
        body: $RELEASE_BODY
        tag_name: $RELEASE_VERSION
        target_commitish: $TRAVIS_COMMIT
        draft: false
        on:
          branch: master
          repo: plus3it/tardigrade-ci
          condition: '"$PRIOR_VERSION" != "$RELEASE_VERSION"'

    - stage: deploy
      name: Deploy docker image to dockerhub
      if: (branch = master OR tag is present) AND type != pull_request AND repo = plus3it/tardigrade-ci
      script: docker build --build-arg GITHUB_ACCESS_TOKEN=$GITHUB_ACCESS_TOKEN -t "$IMAGE_NAME" -f Dockerfile .
      before_deploy:
        - export DOCKERHUB_TARGET="plus3it/tardigrade-ci:${TRAVIS_TAG:-latest}"
        - docker tag "$IMAGE_NAME" "$DOCKERHUB_TARGET"
        - echo Pushing image "$DOCKERHUB_TARGET"
        - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
      after_deploy: echo Pushed image "$DOCKERHUB_TARGET"
      deploy:
        - provider: script
          # push "latest" to dockerhub
          script: docker push "$DOCKERHUB_TARGET"
          skip_cleanup: true
          on:
            branch: master
        - provider: script
          # push "tag" to dockerhub
          script: docker push "$DOCKERHUB_TARGET"
          skip_cleanup: true
          on:
            tags: true
