version: 1

update_configs:

  - package_manager: "docker"
    directory: "/"
    update_schedule: "daily"

  - package_manager: "go:modules"
    directory: "/tests/terraform"
    update_schedule: "daily"
